insert into public.checklist_templates (shift, task_label, icon_name, color_class, bg_class, sort_order)
values
  ('opening', 'Rosted Kunafa', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1001),
  ('opening', 'Make Pistachio sauce', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1002),
  ('opening', 'Refill Syrups and Slush', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1003),
  ('opening', 'Refill milk chocolate', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1004),
  ('opening', 'Prepare Dr.Sweet', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1005),
  ('opening', 'Avocado - Mango - Strawberry', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1006),
  ('opening', 'Prepare all fresh fruits and Fruits salad.', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1007),
  ('opening', 'Pancake mix, Crepe mix', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1008),
  ('opening', 'Prepare Strawberry Chocolate 15 pieces', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1009),
  ('opening', 'Prepare brownie cake for "Hannan-Pillow-Fettuccini"', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1010),
  ('opening', 'Take out croissants from freezer put them in the cooler', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1011),
  ('opening', 'Prepare water for customer', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1012),
  ('opening', 'Prepare the filtered white chocolate.', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1013),
  ('opening', 'Check ice maker and make sure it working well', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1014),
  ('opening', 'Pomegranate seeds', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1015),
  ('opening', 'Check and refill all ice cream machines.', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1016),
  ('opening', 'Clean the foam from ice cream machine', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1017),
  ('opening', 'Refill all bottles chocolate', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1018),
  ('opening', 'Refill all chocolate in bottle, warmer.', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1019),
  ('opening', 'Mix nuts', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1020),
  ('opening', 'Refill cutlery for customer, make sure trash bin of customer good', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1021),
  ('opening', 'Open the sign and DoorDash application.', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1022),
  ('opening', 'Clean all cashier areas, Open back door', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1023),
  ('opening', 'Prepare Açaí and Dubai brownie', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1024),
  ('opening', 'Clean all sweet machine before preparing order for customers', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1025),
  ('opening', 'Stir mango ice cream in ice cream maker', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1026),
  ('opening', 'Prepare sauce: Kinder-Oreo-Pistachio', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1027),
  ('opening', 'Fold Fettuccini box, prepare twin cup', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1028),
  ('opening', 'Cut Kinder chocolate, Prepare all powder, biscuits needed.', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1029),
  ('opening', 'Make sure you have cream for Kunafa', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1030),
  ('opening', 'Make sure you have sugar syrup for Kunafa', 'Sparkles', 'text-pink-600', 'bg-pink-100', 1031),
  ('closing', 'Restock soft drinks', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2001),
  ('closing', 'Refill Syrups and Slush', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2002),
  ('closing', 'Clean the coffee Machine, keep the milk inside fridge', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2003),
  ('closing', 'Clean all refrigerators', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2004),
  ('closing', 'Clean the sweet machines', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2005),
  ('closing', 'Refill all chocolate in bottle, warmer.', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2006),
  ('closing', 'Add frozen strawberries to the refrigerator.', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2007),
  ('closing', 'Remove Avocado, Heart Attact, Emperor', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2008),
  ('closing', 'Clean sealing machine and can sealing machine', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2009),
  ('closing', 'Clean the toilet, dining, and kitchen', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2010),
  ('closing', 'Turn of the sweet machines', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2011),
  ('closing', 'CHECK the warmer temperature', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2012),
  ('closing', 'Lock the back door', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2013),
  ('closing', 'Clean Cashier Area', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2014),
  ('closing', 'Stir mango ice cream in ice cream maker', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2015),
  ('closing', 'Place the ice cream machine on standby mode.', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2016),
  ('closing', 'Keep the cheese in the cooller', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2017),
  ('closing', 'Clean Microwave, cooler and Blender inside kitchen', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2018),
  ('closing', 'Clean all the sink with soap', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2019),
  ('closing', 'TURN OFF the gas', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2020),
  ('closing', 'Clean all towels and apron', 'Sparkles', 'text-purple-600', 'bg-purple-100', 2021)
on conflict (shift, task_label) do update
set
  icon_name = excluded.icon_name,
  color_class = excluded.color_class,
  bg_class = excluded.bg_class,
  sort_order = excluded.sort_order,
  is_active = true;
